#!/bin/sh
#Test identity matrices using the first method for converting to an equivalent path
N=$1
for i in $(eval echo {1..10})
do
    echo "Testing $i/10"
    d="0.$i"
    r="$i\/10"
    ../identity/genidentity $N > input
    for k in $(eval echo {1..$((2*N))})
    do
        echo "Testing label $k \c"
        sed "s/k=.*/k=$k/" input > tmp
        sed 's/1 0/'"$r"' 0/' tmp | sed 's/0 1/0 '"$r"'/' > rinput
        ../../inlh -m < rinput > rpath
        grep -x 'leaving:.*' rpath > tmp
        mv tmp rpath
        sed 's/leaving: \([a-z0-9]*\).*/\1/' rpath > tmp
        mv tmp rpath

        sed "s/k=.*/k=$k/" input > tmp
        sed 's/1 0/'"$d"' 0/' tmp | sed 's/0 1/0 '"$d"'/' > dinput
        ../../inlh -m < dinput > dpath
        grep -x 'leaving:.*' dpath > tmp
        mv tmp dpath
        sed 's/leaving: \([a-z0-9]*\).*/\1/' dpath > tmp
        mv tmp dpath
        S=`diff dpath rpath`
        if [ -z $S ] 
            then
            echo "Passed"
        else
            echo "Failed"
        fi
    done
done
rm *input dpath rpath