#!/bin/sh
echo "\n" > sample-output
for M in $(eval echo 2 4 6)
do
	N=$((2*$M))
	F=$M"x"$N
	echo "Testing $F"
	for k in $(eval echo {1..$(($N+$M))})
	do
		echo "Testing label $k: \c"
		sed "s/k=.*/k=$k/" $F > tmp
		mv tmp $F
		../../../inlh $2 < $F > tmp
		cat sample-output tmp > tmp2
		mv tmp2 sample-output
		C=`egrep 'Number of pivots:' tmp | sed 's/Number of pivots:[ ]* \([0-9]*\)/\1/'`
		#echo $C
		G=`sed -n ''"$k,$k p"'' "$F"path | sed "s/.*length=\([0-9]*\)/\1/"`
		B=$(($G+3))
		if [ $C -eq $B ]
		then
			echo "Passed"
		else
			echo "Failed"
		fi
	done
done
rm -f tmp